spam=[]
spam.append(" good shit go౦ԁ sHit thats ✔ some goodshit rightthere right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 НO0ОଠOOOOOОଠଠOoooᵒᵒᵒ­ᵒᵒᵒᵒᵒᵒ 💯 Good shitsauce me the FUCK up 🍕🍅🍕🍅🍕🍅🍕🍅🍕🍅 cheesy shit cheesy sHit🍕 thats ✔ some cheesy🍕🍕shit right🍕🍕th 🍕 ere🍕🍕🍕 right✔there ✔✔if i do ƽaү so my selｆ 🍴 i say so 🍴 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ🍴 🍕🍕 🍕НO0ОଠＯOOＯOОଠଠOoooᵒᵒ­ᵒᵒᵒᵒᵒᵒᵒ🍕 🍕🍕 🍕 🍴 🍕 🍅🍅🍅 🍕🍕Cheesy shit 👌🎩👓🎩👍🎩👓🎩👍🎩 euphoric logic !euphoric loGic👌 thats ✔ some euphoric👌💻 logic right👌💻there👌👍👌 Carl 🔭 Sagan🌌💫if i do ƽaү so gentlemen 💯 i say so 💯 thats euPhoric logic right there Richard 📒 Dawkins🎩 (chorus: socrates died for this shit) mMMMMᎷМ💯 👌👓👌НO0ОଠOOOOOОଠଠOooo­ᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌🎩 👌 💯 👌 👓🎩🎩🎩 👍👌euphoric logic slam me the FUCK uP 👌👀👌👀👌👀👌👀👌👀 john cena JOhN cEna👌 john ✔ cena john👌👌cena john👌👌cena👌👌👌 john✔cena ✔✔u can't see me if I do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒ­ᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌John ceNa POTENTIALLY sign me the FUCK up 👋👀👋👀👋👀👋👀👋👀 average shit modera̷̶te sHit 👋 thats some ALright 👋👋shit right 👋👋 th 👋 ere 👋👋👋 right 🆗 there 🆗 if i do ƽaү so my selｆ🆗 i say so 🆗 that could be what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ 🆗 👋 👋👋НO0ОଠＯOOＯOОଠଠOoooᵒ­ᵒᵒᵒᵒᵒᵒᵒᵒ 👋 👋👋 👋 🆗 👋 👀 👀 👀 👋👋Not outstanding shit 👌👽👌👽👌👽 ayy lmao ayyy lmao good lmao👌 thats ✔ some ayyy👌👌lamayo right👌👌there👌👌👌 right✔there ✔✔if i do LMAO so my self 💯 i ayyy so 💯 thats what im probing about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌AAAYYYYyyyyYYYYYyyy­yyyʸʸʸʸʸʸʸʸ👌 👌👌 👌 💯 👌 👽👽👽👌👌ayy lmao 🐸♊️🐸♊️🐸♊️🐸♊️🐸♊️ g")
spam.append("░░░░░░░░░░░▄▀▀▀▀▀▀▀▀­▀▀▀▀▀▀▄░░░░░░░░░░░ ░░░░░░░░▄▀░░░░░░░░░░­░░░▒▒▒▒▒▄░░░░░░░░░ ░░░░░░▄▀▒▒▒▒░░░░▒▒▒▒­▒▒▒▒▒▒▒▒▒█░░░░░░░░ ░░░░░█▒▒▒▒░░░░▒▒▒▒▒▒­▒▒▒▒░░░░▒▒█░░░░░░░ ░░░░█▒▒▄▀▀▀▀▀▄▄▒▒▒▒▒­▒▒▒▒▄▄▀▀▀▀▀▀▄░░░░░ ░░▄▀▒▒▒▄█████▄▒█▒▒▒▒­▒▒▒█▒▄█████▄▒█░░░░ ░█▒▒▒▒▐██▄████▌▒█▒▒▒­▒▒█▒▐██▄████▌▒█░░░ ▀▒▒▒▒▒▒▀█████▀▒▒█▒░▄­▒▄█▒▒▀█████▀▒▒▒█░░ ▒▒▐▒▒▒░░░░▒▒▒▒▒█▒░▒▒­▀▒▒█▒▒▒▒░░░░▒▒▒▒█░ ▒▌▒▒▒░░░▒▒▒▒▒▄▀▒░▒▄█­▄█▄▒▀▄▒▒▒░░░░▒▒▒▒▌ ▒▌▒▒▒▒░▒▒▒▒▒▒▀▄▒▒█▌▌­▌▌▌█▄▀▒▒▒▒▒░░░▒▒▒▐ ▒▐▒▒▒▒▒▒▒▒▒▒▒▒▒▌▒▒▀█­██▀▒▌▒▒▒▒▒▒▒▒▒▒▒▒▌ ▀▀▄▒▒▒▒▒▒▒▒▒▒▒▌▒▒▒▒▒­▒▒▒▒▐▒▒▒▒▒▒▒▒▒▒▒█░ ▀▄▒▀▄▒▒▒▒▒▒▒▒▐▒▒▒▒▒▒­▒▒▒▄▄▄▄▒▒▒▒▒▒▄▄▀░░ ▒▒▀▄▒▀▄▀▀▀▄▀▀▀▀▄▄▄▄▄­▄▄▀░░░░▀▀▀▀▀▀░░░░░ ▒▒▒▒▀▄▐▒▒▒▒▒▒▒▒▒▒▒▒▒­▐░░░░░░░░░░░░░░░░░ayy lmao")
spam.append(" IF YOU SEE THIS MESSAGE WHILE SCROLLING you have been visited by trumpet skeleton of the abyss good bones and calcium will come to you but only if you reply 'thank mr skeltal to this message and spread it to 3 more circlejerk posts!!good shit go౦ԁ sHit thats ✔ some good👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒ­ᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit OP, good karma whoring👌 👌")
spam.append("WHAT ARE YOU DOING IN MY SWAMP???????????????­????????????????????­????????????????????­????????????????????­????????????????????­????????????????????­????????????????????­???????????????? ????????????????????­????????????????????­??? ????????????????????­????????????????????­????????????????????­????????????????????­????????????????????­????????????????????­????????????????????­????????????????????­????????????????????­??????????????????? ????????????????????­????????????????????­??? ????????????????????­????????????????????­????????????????????­????????????????????­????????????????????­????????????????????­????????????? ????????????????????­????????????????????­??? ????????????????????­????????????????????­????????????????????­????????????????????­?????????? ????????????????????­????????????????????­??")
spam.append("WTF were you even thinking posting this sub quality meme on one of my favorite anime forums? I'll have you know that by the time I was 11 I had already finished Naruto, Bleach, every Dragonball series, as well as countless other quality anime. I even had the best limited edition figurines that my parent's money could buy from REAL series such as Deathnote, and the TMNTurtles vintage 1987 edition of Raph. Don't even get me started on your <anime experience.> Look I'm not trying to be overly rude or anything. I'll always encourage people trying to get into Anime, and I am usually quite the patient and understanding man, I honestly try to relate and befriend people such as yourself on most occasions for at least a month, or however long it takes for me to deem them worthy or unworthy of the sweet blessing that is anime, but this? This is unacceptable and downright OFFENSIVE to my culture and everything I stand for as a devout anime viewer and Manga reader (I'll return to this topic in a bit, don't worry.) You think you know anime? You think you're a real fan? Never in my entire 16 years of living have I ever seen something more PATHETIC than THIS. Honestly with posts like this I can surmise that your character is nothing more that of my parents, or old friends who just couldn't accept me for who I am. I've known your type ever since the fourth grade when my heart was destroyed by the girl who was actually TOTALLY INTO ME, that was of course until I showed her my storage closet full of only the highest quality clippings of my Shōnen✩Jump collection. You're just a shallow, shallow man, just like Haretchi-Chan of my own Independently produced Manga. Not that I expect you to have even the slightest clue what I'm talking about. This an advanced and highly evolved form of entertainment, and if you can not appreciate it as such then I have no interest in your <contributions< to this forum, sir. Now lets take a look at the animaiecal achievements of a true civilized Animatio")
spam.append("""
 IF YOU SEE THIS MESSAGE WHILE SCROLLING you have been visited by trumpet skeleton of the abyss good bones and calcium will come to you but only if you reply "thank mr skeltal" to this message and spread it to 3 more circlejerk posts!!

good shit go౦ԁ sHit thats ✔ some good👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒ­ᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit OP, good karma whoring👌 👌""")
spam.append("""

＼＼
＼＼
＼(ಠ益ಠ)
/ \
/ へ＼
/ / ＼＼
/ ノ ヽ_つ ayy lmao
/ / \
/ / \ \
( / \ \
| | \ ＼
| 丿 ＼⌒)
| | ) /
/ ) Lﾉ﻿
| /
Lﾉ﻿""")

